Implemented auth
code-gambit/VT-WebClient pull request #29
Opened 2021-05-15 11:34 UTC by ayush0x00

# Description

Added user authentication functionality

Fixes #27 

## Type of change

Please delete options that are not relevant.

- [ ] Updated UI/UX
- [ ] Improved the business logic of code
- [x] Added new feature
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-05-15 12:35 UTC, lakshya-20 commented
@ayush0x00 what is `#current-cloud-backend` folder in amplify folder?

2021-05-15 12:46 UTC, lakshya-20 commented
- Also, resize the elements in Login and Signup Components. Currently, they are spanning to the whole browser width.
- Also update Toasts as mentioned above.
![image](https://user-images.githubusercontent.com/39180629/118361421-0866fe00-b5a9-11eb-9b3c-45ec5fc12250.png)

2021-05-15 12:47 UTC, lakshya-20 commented
I cloned your pr after signing up when I refresh the page I have to again login into the application. Please look into and resolve it.

2021-05-15 12:50 UTC, lakshya-20 commented
Use `Toasts` to display greetings(simple message) when the user signin or singup.

2021-05-15 16:40 UTC, ayush0x00 commented
> @ayush0x00 what is `#current-cloud-backend` folder in amplify folder?
The amplify folder is built while setting up authentication using cognito. Its all default configuration.

2021-05-16 14:18 UTC, lakshya-20 commented
- Above mentioned events are still not rectified.
- Still, toasts are not updated in `Signup.js` and `Signin.js`, and elements are not aligned properly.
![image](https://user-images.githubusercontent.com/39180629/118400273-8812cc80-b67e-11eb-8deb-a960260eb417.png)
- `Signin` component is not designed properly 
![image](https://user-images.githubusercontent.com/39180629/118400311-b8f30180-b67e-11eb-8518-695f32aa5bb8.png)
- I tried to log in to the application with the correct credentials but I got this error and Please display some meaningful and user-friendly messages.
![image](https://user-images.githubusercontent.com/39180629/118400487-74b43100-b67f-11eb-8f86-99356e84a9d7.png)

2021-05-16 14:24 UTC, lakshya-20 requested changes

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignIn.js
> +            }}
No need for this Event

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignIn.js
> +            }}
This too 
This is making UI ridiculous.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignIn.js
> +            }}
No need of this event

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +            }}
No need for this event.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +            }}
This too

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +            }}
This too

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +            }}
Why have you added this?
It is displaying errors by just moving the cursor through UI.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +        </div>
Use [https://www.npmjs.com/package/react-toastify](https://www.npmjs.com/package/react-toastify)
As used in other components.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +    </div>
Use [https://www.npmjs.com/package/react-toastify](https://www.npmjs.com/package/react-toastify)
As used in other components.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignIn.js
> +    </div>
Use [https://www.npmjs.com/package/react-toastify](https://www.npmjs.com/package/react-toastify)
As used in other components.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignIn.js
> +        >
Instead of conditionally disabling the button. Make the button, when clicked, pass a validation before calling the handleSubmit function.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +        >
Instead of conditionally disabling the button. Make the button, when clicked, pass a validation before calling the handleSubmit function.

2021-05-16 14:24 UTC, lakshya-20 commented on src/Components/Screens/SignUp.js
> +      </Form>
Don't render it, use 2-page process like
- 1st page to get the details
- 2nd page to confirm the user. (this can be done using conditional rendering)
This way it looks cool.
Current UI (not user friendly and spanning through whole width):  
![image](https://user-images.githubusercontent.com/39180629/118361912-f9814b00-b5aa-11eb-992b-c2b57d45ab97.png)

2021-05-17 12:18 UTC, lakshya-20 commented
- Toasts are still not modified
![image](https://user-images.githubusercontent.com/39180629/118486092-d4b9de80-b736-11eb-9743-b740b25d6359.png)
- Both passwords are the same but still
![image](https://user-images.githubusercontent.com/39180629/118486775-9e309380-b737-11eb-8a5b-ff8816e6c719.png)

2021-05-17 20:11 UTC, lakshya-20 approved these changes

2021-05-17 20:11 UTC, merged