fixed footer component
code-gambit/VT-WebClient pull request #64
Opened 2021-06-06 14:54 UTC by ayush0x00

# Description

Modified footer component to add auth features.

Fixes #50 #38 

## Type of change

Please delete options that are not relevant.

- [x] Updated UI/UX
- [ ] Improved the business logic of code
- [x] Added new feature
- [ ] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-06 16:46 UTC, lakshya-20 reviewed
![image](https://user-images.githubusercontent.com/39180629/120932708-82a42180-c714-11eb-895f-06cb48c61d54.png)

This tab modal is not responsive in small devices, so add a modal header like `Update` or `change` or `whats looks suitable` and remove that change from tab headings. It will work then.

2021-06-06 16:48 UTC, lakshya-20 commented
#50  is linked but not resolved with this PR. Any of the mentioned requirements are not fulfilled by this PR.

2021-06-06 16:51 UTC, lakshya-20 requested changes
Your Footer
![image](https://user-images.githubusercontent.com/39180629/120932859-34435280-c715-11eb-8054-7d59ca83e629.png)

The current deployed Footer
![image](https://user-images.githubusercontent.com/39180629/120932889-44f3c880-c715-11eb-99ff-43539772e5e1.png)
The above snips are taken from the same screen ratio.
Notice the difference in the gap around toggle icons.

2021-06-06 16:58 UTC, lakshya-20 requested changes
https://user-images.githubusercontent.com/39180629/120933125-483b8400-c716-11eb-96d4-c6c59b754744.mp4

Reset the states when switching the tabs.

2021-06-06 17:03 UTC, lakshya-20 commented
@ayush0x00 don't forget to add labels and adding this PR to the project.

2021-06-07 17:14 UTC, danishjamal104 approved these changes, later dismissed
Looks good, make sure the footer icons and email have valid redirecting URLs.

2021-06-07 17:15 UTC, danishjamal104 commented
@ayush0x00 , please rebase.

2021-06-07 17:55 UTC, lakshya-20 requested changes
Modularize the code, it becomes easy to understand the modular code and will help to add any new feature.

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +  ModalHeader,
Don't import ModalHeader and ModalFooter they are not being used anywhere.

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +  const [code, sendCode] = useState(false);
This hook declaration is not used anywhere so remove it.

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +              <Form style={{ "margin-top": "5px" }} onSubmit={updatePassword}>
![image](https://user-images.githubusercontent.com/39180629/121064327-0cbbbb00-c7e5-11eb-9cee-754423dea845.png)

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +                    <p style={{ "text-align": "left" }}>
![image](https://user-images.githubusercontent.com/39180629/121064496-4bea0c00-c7e5-11eb-8bed-d766efb65a3c.png)

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +                    <p style={{ "text-align": "left" }}>{errors.password}</p>
![image](https://user-images.githubusercontent.com/39180629/121064525-54424700-c7e5-11eb-947c-cdd0e57cdd42.png)

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +                    <p style={{ "text-align": "left" }}>
![image](https://user-images.githubusercontent.com/39180629/121064541-5ad0be80-c7e5-11eb-9b3e-a0c3865f05d3.png)

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +              <Form style={{ "margin-top": "5px" }} onSubmit={updateUsername}>
![image](https://user-images.githubusercontent.com/39180629/121064812-a8e5c200-c7e5-11eb-90ec-b7b091bb10dd.png)

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +  };
Instead of requesting amplify to update the username first check locally is username empty or not than request.

2021-06-07 17:55 UTC, lakshya-20 commented on src/Components/Footer.js
> +          <div className="col-12 col-sm-4 d-flex  align-items-center justify-content-center">v-transfer-demo@gmail.com</div>
Change this using email tag [Can refer to this](https://www.tutorialspoint.com/html/html_email_links.htm)

2021-06-08 05:13 UTC, lakshya-20 requested changes
![image](https://user-images.githubusercontent.com/39180629/121126103-402e3200-c845-11eb-889e-8e4f7b34ed63.png)
Show the errors with a meaningful message from the user point of view.

2021-06-08 05:13 UTC, lakshya-20 commented on src/Components/Footer.js
> +          <div className="col-12 col-sm-4 d-flex  align-items-center justify-content-center"><a href = "mailto: code.gb.io@gmail.com">Send us an inbox</a></div>
Instead of "Send us an inbox" write the mail id.

2021-06-08 05:14 UTC, lakshya-20 commented
@ayush0x00 do update your branch

2021-06-08 21:50 UTC, lakshya-20 approved these changes
LGTM

2021-06-08 21:52 UTC, merged